In [1]:
import pandas as pd  

dataset = [
    ['Milk', 'Bread', 'Butter'],
    ['Bread', 'Butter'],
    ['Milk', 'Bread'],
    ['Milk', 'Butter'],
    ['Bread', 'Butter', 'Eggs'],
    ['Milk', 'Eggs'],
    ['Bread', 'Eggs'],
    ['Milk', 'Bread', 'Butter', 'Eggs']
]
df = pd.DataFrame(dataset)

In [2]:
from mlxtend.preprocessing import TransactionEncoder

te = TransactionEncoder()
te_array = te.fit(dataset).transform(dataset)

df_encoded = pd.DataFrame(te_array, columns=te.columns_)

In [4]:
from mlxtend.frequent_patterns import apriori 

frequent_itemsets = apriori(
    df_encoded,
    min_support=0.3,
    use_colnames=True
)
print(frequent_itemsets)

   support         itemsets
0    0.750          (Bread)
1    0.625         (Butter)
2    0.500           (Eggs)
3    0.625           (Milk)
4    0.500  (Butter, Bread)
5    0.375    (Eggs, Bread)
6    0.375    (Milk, Bread)
7    0.375   (Milk, Butter)

In [7]:
from mlxtend.frequent_patterns import association_rules

rules = association_rules(
    frequent_itemsets,
    metric='confidence',
    min_threshold=0.6
)

rules[['antecedents', 'support', 'confidence', 'lift']]

  antecedents  support  confidence      lift
0     (Bread)    0.500    0.666667  1.066667
1    (Butter)    0.500    0.800000  1.066667
2      (Eggs)    0.375    0.750000  1.000000
3      (Milk)    0.375    0.600000  0.800000
4      (Milk)    0.375    0.600000  0.960000
5    (Butter)    0.375    0.600000  0.960000

In [8]:
rules[['antecedents', 'consequents', 'support']]

  antecedents consequents  support
0     (Bread)    (Butter)    0.500
1    (Butter)     (Bread)    0.500
2      (Eggs)     (Bread)    0.375
3      (Milk)     (Bread)    0.375
4      (Milk)    (Butter)    0.375
5    (Butter)      (Milk)    0.375

In [9]:
rules[['antecedents', 'consequents', 'confidence']]

  antecedents consequents  confidence
0     (Bread)    (Butter)    0.666667
1    (Butter)     (Bread)    0.800000
2      (Eggs)     (Bread)    0.750000
3      (Milk)     (Bread)    0.600000
4      (Milk)    (Butter)    0.600000
5    (Butter)      (Milk)    0.600000

In [10]:
rules[['antecedents', 'consequents', 'lift']]

  antecedents consequents      lift
0     (Bread)    (Butter)  1.066667
1    (Butter)     (Bread)  1.066667
2      (Eggs)     (Bread)  1.000000
3      (Milk)     (Bread)  0.800000
4      (Milk)    (Butter)  0.960000
5    (Butter)      (Milk)  0.960000

In [12]:
strong_rules = rules[rules['lift'] > 1.2]
strong_rules[['antecedents', 'support', 'confidence', 'lift']]

Empty DataFrame
Columns: [antecedents, support, confidence, lift]
Index: []